// Getters
export const GETTERS_GET_SHOWS = 'GETTERS_GET_SHOWS';
export const GETTERS_GET_AUTH = 'GETTERS_GET_AUTH';
export const GETTERS_GET_USER = 'GETTERS_GET_USER';
export const GETTERS_CURRENT_SHOW_ITEM = 'GETTERS_CURRENT_SHOW_ITEM';

// Mutations
export const MUTATION_GET_SHOWS = 'MUTATION_GET_SHOWS';
export const MUTATION_ADD_COMMENT = 'MUTATION_ADD_COMMENT';
export const MUTATION_CHANGE_AUTH = 'MUTATION_CHANGE_AUTH';
export const MUTATION_CHANGE_CURRENT_SHOW_ITEM = 'MUTATION_CHANGE_CURRENT_SHOW_ITEM';
export const MUTATION_SING_UP_USER = 'MUTATION_SING_UP_USER';
export const MUTATION_LOAD_USER_DB = 'MUTATION_LOAD_USER_DB';

// Actions
export const ACTION_GET_SHOWS = 'ACTION_GET_SHOWS';
export const ACTION_ADD_COMMENT = 'ACTION_ADD_COMMENT';
export const ACTION_CHANGE_AUTH = 'ACTION_CHANGE_AUTH';
export const ACTION_CHANGE_CURRENT_SHOW_ITEM = 'ACTION_CHANGE_CURRENT_SHOW_ITEM';
export const ACTION_SING_UP_USER = 'ACTION_SING_UP_USER';
export const ACTION_LOAD_USER_DB = 'ACTION_LOAD_USER_DB';