// Getters
export const GETTERS_GET_SHOWS = 'GETTERS_GET_SHOWS';
export const GETTERS_CURRENT_ITEM = 'GETTERS_CURRENT_ITEM';
export const GETTERS_GET_AUTH = 'GETTERS_GET_AUTH';
export const GETTERS_GET_USER = 'GETTERS_GET_USER';
export const GETTERS_CURRENT_SHOW_ITEM = 'GETTERS_CURRENT_SHOW_ITEM';

// Mutations
export const MUTATION_GET_SHOWS = 'MUTATION_GET_SHOWS';
export const MUTATION_CURRENT_ITEM = 'GETTERS_CURRENT_ITEM';
export const MUTATION_ADD_COMMENT = 'GETTERS_ADD_COMMENT';
export const MUTATION_CHANGE_AUTH = 'MUTATION_CHANGE_AUTH';
export const MUTATION_CHANGE_CURRENT_SHOW_ITEM = 'MUTATION_CHANGE_CURRENT_SHOW_ITEM';

// Actions
export const ACTION_GET_SHOWS = 'ACTION_GET_SHOWS';
export const ACTION_CURRENT_ITEM = 'GETTERS_CURRENT_ITEM';
export const ACTION_ADD_COMMENT = 'GETTERS_ADD_COMMENT';
export const ACTION_CHANGE_AUTH = 'ACTION_CHANGE_AUTH';
export const ACTION_CHANGE_CURRENT_SHOW_ITEM = 'ACTION_CHANGE_CURRENT_SHOW_ITEM';
